easy_admin:
    design:
        assets:
            css:
                - 'build/easy_admin.css'

        menu:
            - entity: User
            - label: Jira
              route: jira_index
            - label: Portal
              route: portal_index

    entities:
        User:
            controller: App\Controller\UserController

            class: App\Entity\User
            label: portal.user

            list:
                actions: ['notifyUserCreated', 'resetPassword']

                fields:
                    - property: email
                      label: portal.user.email
                    - property: roles
                      label: portal.user.roles
                    - property: enabled
                      label: portal.user.enabled
                      type: boolean
                    - property: portalApps
                      label: portal.user.portalApps
                    - property: lastLogin
                      label: portal.user.lastLogin

            new:
                fields:
                    - property: email
                      label: portal.user.email
                    - property: roles
                      label: portal.user.roles
                      type: App\Form\UserRolesType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: portalApps
                      label: portal.user.portalApps
                      type: App\Form\PortalAppsType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: fullName
                      label: portal.user.fullName
                    - property: department
                      label: portal.user.department
                    - property: address
                      label: portal.user.address
                    - property: postalCode
                      label: portal.user.postalCode
                    - property: city
                      label: portal.user.city
                    - property: usedDebtors
                      label: portal.user.debtors
                      type: 'easyadmin_autocomplete'
                      type_options:
                          by_reference: false
                          class: 'GraphicServiceOrder\Entity\Debtor'
                          multiple: true
                    - property: noDefaultSettings
                      label: portal.user.noDefault

            edit:
                fields:
                    - property: email
                      label: portal.user.email
                    - property: enabled
                      label: portal.user.enabled
                    - property: roles
                      label: portal.user.roles
                      type: App\Form\UserRolesType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: portalApps
                      label: portal.user.portalApps
                      type: App\Form\PortalAppsType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: fullName
                      label: portal.user.fullName
                    - property: department
                      label: portal.user.department
                    - property: address
                      label: portal.user.address
                    - property: postalCode
                      label: portal.user.postalCode
                    - property: city
                      label: portal.user.city
                    - property: usedDebtors
                      label: portal.user.debtors
                      type: 'easyadmin_autocomplete'
                      type_options:
                        by_reference: false
                        class: 'GraphicServiceOrder\Entity\Debtor'
                        multiple: true
                    - property: noDefaultSettings
                      label: portal.user.noDefault
        Debtor:
          class: GraphicServiceOrder\Entity\Debtor
