easy_admin:
    design:
        menu:
            - entity: User
            - label: Jira
              route: jira_index
            - label: Portal
              route: portal_index

    entities:
        User:
            class: App\Entity\User

            list:
                fields:
                    - property: email
                    - property: roles
                    - property: enabled
                    - property: portalApps
                    - property: lastLogin

            form:
                fields:
                    - property: email
                    - property: roles
                    - property: portalApps
                      type: App\Form\PortalAppsType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: enabled
