easy_admin:
    design:
        menu:
            - entity: User
            - label: Jira
              route: jira_index
            - label: Portal
              route: portal_index

    entities:
        User:
            class: App\Entity\User

            list:
                fields:
                    - property: email
                    - property: roles
                    - property: enabled
                    - property: lastLogin

            form:
                fields:
                    - property: email
                    - property: roles
                    - property: portals
                      # @TODO: Make this work!
                      type: App\Form\PortalsType
                      type_options:
                          multiple: true
                          expanded: true
                          # portals: '%portals%'
                    - property: enabled
