easy_admin:
    design:
        assets:
            css:
                - 'build/easy_admin.css'

        menu:
            - entity: User
            - label: Jira
              route: jira_index
            - label: Portal
              route: portal_index

    entities:
        User:
            controller: App\Controller\UserController

            class: App\Entity\User
            label: portal.user

            list:
                actions: ['notifyUserCreated', 'resetPassword']

                fields:
                    - property: email
                      label: portal.user.email
                    - property: roles
                      label: portal.user.roles
                    - property: enabled
                      label: portal.user.enabled
                      type: boolean
                    - property: portalApps
                      label: portal.user.portalApps
                    - property: lastLogin
                      label: portal.user.lastLogin
                    - property: UserFullName
                      label: portal.user.UserFullName
                    - property: UserDepartment
                      label: portal.user.UserDepartment
                    - property: UserAddress
                      label: portal.user.UserAddress
                    - property: UserPostalCode
                      label: portal.user.UserPostalCode
                    - property: UserCity
                      label: portal.user.UserCity
                    - property: UserAccount
                      label: portal.user.UserAccount

            new:
                fields:
                    - property: email
                      label: portal.user.email
                    - property: roles
                      label: portal.user.roles
                      type: App\Form\UserRolesType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: portalApps
                      label: portal.user.portalApps
                      type: App\Form\PortalAppsType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: UserFullName
                      label: portal.user.UserFullName
                    - property: UserDepartment
                      label: portal.user.UserDepartment
                    - property: UserAddress
                      label: portal.user.UserAddress
                    - property: UserPostalCode
                      label: portal.user.UserPostalCode
                    - property: UserCity
                      label: portal.user.UserCity
                    - property: UserAccount
                      label: portal.user.UserAccount
                      type: App\Form\PortalAccountType
                      type_options:
                        multiple: false
                        expanded: false

            edit:
                fields:
                    - property: email
                      label: portal.user.email
                    - property: enabled
                      label: portal.user.enabled
                    - property: roles
                      label: portal.user.roles
                      type: App\Form\UserRolesType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: portalApps
                      label: portal.user.portalApps
                      type: App\Form\PortalAppsType
                      type_options:
                          multiple: true
                          expanded: true
                    - property: UserFullName
                      label: portal.user.UserFullName
                    - property: UserDepartment
                      label: portal.user.UserDepartment
                    - property: UserAddress
                      label: portal.user.UserAddress
                    - property: UserPostalCode
                      label: portal.user.UserPostalCode
                    - property: UserCity
                      label: portal.user.UserCity
                    - property: UserAccount
                      label: portal.user.UserAccount
                      type: App\Form\PortalAccountType
                      type_options:
                        multiple: false
                        expanded: false
