fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        user_manager: ItkDev\UserManagementBundle\Doctrine\UserManager
    from_email:
        address: '%mailer_email%'
        sender_name: '%mailer_name%'

    registration:
        form:
            type: App\Form\RegistrationFormType

    profile:
        form:
            type: App\Form\ProfileFormType
