# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        # This is a mapping example, remove it and create your own mappings.
        gsorder:
            frontend: blueimp
            storage:
                directory: "%kernel.root_dir%/../private/files/gs/tmp"