security:
    providers:
        oauth_user_provider:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jira_secured_area:
            pattern: ^/jira
            anonymous: ~
            oauth:
                resource_owners:
                    jira:          /jira/login/check
                login_path:        /jira/login
                check_path:        /jira/login/check
                use_forward:       false
                failure_path:      /jira/login
                oauth_user_provider:
                    service: hwi_oauth.user.provider


    access_control:
        - { path: ^/jira/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jira/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
