security:
    role_hierarchy:
        ROLE_JIRA:        ROLE_USER
        ROLE_ADMIN:       ROLE_JIRA
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        oauth_user_provider:
            id: hwi_oauth.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jira_secured_area:
            pattern: ^/jira
            anonymous: ~
            oauth:
                provider: oauth_user_provider
                resource_owners:
                    jira:          /jira/login/check
                login_path:        /jira/login
                check_path:        /jira/login/check
                use_forward:       false
                failure_path:      /jira/login
                oauth_user_provider:
                    service: hwi_oauth.user.provider

        portal_secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: fos_userbundle
            logout: ~

    access_control:
        - { path: ^/jira/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jira/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
