vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        gs_file:
            uri_prefix: /files/gs
            upload_destination: '%kernel.project_dir%/private/files/gs'