services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $boundReceiverAccount: '%gs_billing_receiver_account%'
            $boundReceiverPSP: '%gs_billing_receiver_psp%'
            $boundProjectId: '%gs_billing_project_id%'
            $boundMaterialId: '%gs_billing_material_id%'
            $boundWorklogPricePerHour: '%gs_billing_worklog_hour_price%'

    GraphicServiceBilling\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    GraphicServiceBilling\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
