services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    GraphicServiceOrder\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    GraphicServiceOrder\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
