services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $ownCloudFilesFolder: '%env(OWNCLOUD_FILES_FOLDER)%'
            $gsOrderConfiguration: '%gsorder_bundle%'

    GraphicServiceOrder\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    GraphicServiceOrder\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    GraphicServiceOrder\Service\FileUploader:
        arguments:
            $targetDirectory: '%env(resolve:GS_FILES_DIRECTORY)%'
