hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix:   /login

jira_login:
    path: /login/check-jira

billing:
    resource: "@BillingBundle/Resources/config/routing.yaml"

create-project:
    resource: "@CreateProjectBundle/Resources/config/routing.yaml"

create-graphic-service-order:
    resource: "@GraphicServiceOrderBundle/Resources/config/routing.yaml"

planning:
    resource: "@PlanningBundle/Resources/config/routing.yaml"

expense:
    resource: "@ExpenseBundle/Resources/config/routing.yaml"
