hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /jira/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix:   /jira/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix:   /jira/login

jira_login:
    path: /jira/login/check

billing:
    prefix: /jira
    resource: "@BillingBundle/Resources/config/routing.yaml"

create-project:
    prefix: /jira
    resource: "@CreateProjectBundle/Resources/config/routing.yaml"

create-graphic-service-order:
    resource: "@GraphicServiceOrderBundle/Resources/config/routing.yaml"

planning:
    prefix: /jira
    resource: "@PlanningBundle/Resources/config/routing.yaml"

expense:
    prefix: /jira
    resource: "@ExpenseBundle/Resources/config/routing.yaml"

sprint_report:
    prefix: /jira
    resource: "@SprintReportBundle/Resources/config/routing.yaml"

graphic_service_billing:
    prefix: /jira
    resource: "@GraphicServiceBillingBundle/Resources/config/routing.yaml"
